version: '3.8'

services:
  web-babeo:
    build: .
    container_name: web-babeo-app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    stdin_open: true
    tty: true 